# Generated by Django 5.0.2 on 2024-06-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rollno', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('email', models.EmailField(default='default@example.com', max_length=225)),
                ('econtact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
